export const GARMENT_TYPE_JACKET = 'JACKET'
export const GARMENT_TYPE_WAISTCOAT = 'WAISTCOAT'
export const GARMENT_TYPE_SHIRT = 'SHIRT'
export const GARMENT_TYPE_TROUSERS = 'TROUSERS'
export const GARMENT_TYPE_ALL = [
  GARMENT_TYPE_JACKET,
  GARMENT_TYPE_WAISTCOAT,
  GARMENT_TYPE_SHIRT,
  GARMENT_TYPE_TROUSERS
]
