export const MEASUREMENT_TYPE_BODY = 'BODY'
export const MEASUREMENT_TYPE_GARMENT = 'GARMENT'
export const MEASUREMENT_TYPE_SAMPLE_ADJUSTMENT = 'SAMPLE_ADJUSTMENT'
export const MEASUREMENT_TYPE_ALTERATION = 'ALTERATION'
export const MEAUSREMENT_TYPE_ALL = [
  MEASUREMENT_TYPE_BODY,
  MEASUREMENT_TYPE_GARMENT,
  MEASUREMENT_TYPE_SAMPLE_ADJUSTMENT,
  MEASUREMENT_TYPE_ALTERATION
]
