export const MEASUREMENT_PROFILE_TYPE_BODY = 'BODY'
export const MEASUREMENT_PROFILE_TYPE_GARMENT = 'GARMENT'
export const MEASUREMENT_PROFILE_TYPE_ALL = [
  MEASUREMENT_PROFILE_TYPE_BODY,
  MEASUREMENT_PROFILE_TYPE_GARMENT
]

export function isMeasurementProfileTypeBody (type) {
  return type === MEASUREMENT_PROFILE_TYPE_BODY
}
